version: '3.8'            # Version 3.8 is quite new and should work

services:
  app:                    # The name of the service, can be anything
    image: todo-backend # Declares which image to use
    build: .              # Declares where to build if image is not found
    ports:
      - "3000:3000"

    network_mode: bridge
